config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users
  resources :sessions
  delete '/exit' => 'sessions#destroy', as: :logout # as决定具名路由, 第一个'/exit' 决定路由

  resources :categories, only: [:show]
  resources :products, only: [:show]

  namespace :admin do
    root 'sessions#new'
    resources :sessions
    resources :categories
    resources :products do
      resources :product_images, only: [:index, :create, :destroy, :update]
    end
  end
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">蛋人商城</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= root_path %>">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#">分类</a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="商品名称..">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">购物车</a></li>
        <% unless logged_in? %>
          <li><a href="<%= new_user_path %>">注册</a></li>
          <li><a href="<%= new_session_path %>">登录</a></li>
        <% else %>
          <li><a href="#">欢迎你,<%= current_user.username %></a></li>
          <li><%= link_to "退出", logout_path, method: :delete %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">个人中心 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">我的订单</a></li>
            <li><a href="#">我的收获地址</a></li>
            <li><a href="#">我的收藏</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">个人信息</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>蛋人商城</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0,
    maximum-scale=1.0,user-scalable=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= yield :stylesheets %>
  </head>

  <body>
    <%= render 'layouts/menu' %>
    <div class="container">
      <% unless flash[:notice].blank? %>
        <div class="alert alert-info"><%=  flash[:notice] %></div>
      <% end %>
      
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= yield :javascripts %>
  </body>
</html>